#:schema node_modules/wrangler/config-schema.json
name = "contacts-test"
compatibility_date = "2024-08-06"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "contacts-test"
database_id = "2094c570-8df9-4935-bc08-24c2dff41529"
